apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  postgres_host: postgres.cnk6jwfdyniz.us-east-1.rds.amazonaws.com
  postgres_db: postgres
  aws_bucket: test-dev-2022
  aws_region: us-east-1
  aws_profile: default
  URL: http://a89e19233c7ae4271832f4449c910b47-405153774.us-east-1.elb.amazonaws.com:8100